### PR TITLE
Install fonts only

### PR DESCRIPTION
**Pull request by gnuletik**
Hi !

Thanks for this fork which is really useful !

I recently needed to upgrade an app to the heroku-22 stack (which is already supported upstream on https://github.com/jontewks/puppeteer-heroku-buildpack).

To avoid merging upstream changes and adding support for heroku-22 stack here, I used a different strategy which seems lighter.

This buildpack can only be used to install fonts and we can keep the upstream buildpack to install puppeteer libraries.
This can be configured with:
```sh
# clear cache and current buildpacks
heroku builds:cache:purge
heroku buildpacks:clear

# upstream buildpack for puppeteer
heroku buildpacks:add -i 1 jontewks/puppeteer

# my current fork, but if merged, it could be renamed to
# https://github.com/CoffeeAndCode/puppeteer-extra-fonts
heroku buildpacks:add -i 2 https://github.com/gnuletik/puppeteer-heroku-buildpack

# any other apps buildpack
heroku buildpacks:add -i 3 heroku/nodejs
```

This has been tested on my app without any issue.

What do you think ?

If you're okay with that, I can finish this PR by updating the README, and I think that you should rename this repo.

### CODE REVIEW

**Comment by jonknapp** [comment]
I love this approach. My fork has drifted so far from mainline that I'm concerned it will be more harmful for people than helpful. I wonder if it would be better to coordinate something with @jontewks so that either 1) the main buildpack can handle font installation, or 2) a separate buildpack can be introduced that just focuses on adding fonts (if there's not one already).

I think ideally, we'd do one of the two options (whatever people agree on) and then I can deprecate my buildpack fork since it hasn't been shown the attention it needs.

**Comment by gnuletik** [comment]
Thanks for the fast reply!

Last time, @jontewks [did not agree](https://github.com/jontewks/puppeteer-heroku-buildpack/issues/2#issuecomment-339735302) on adding the extra 22MB of fonts on the buildpack.

This PR is about `2)` if you want to keep maintaining this. I can also host this repo on my username if you don't.

**Comment by jonknapp** [comment]
I can understand not wanting to unnecessarily bloat the original buildpack. If you wanted to make a buildpack that only adds fonts I say go for it! Please let me know when it’s done and I can update my readme and deprecate this project.

I would also recommend making a pull request to the original buildpack to add to its readme about the new way to add fonts using your buildpack.

Thanks for making a better looking solution!



----- Original message -----

**Comment by gnuletik** [comment]
Here is the repo: https://github.com/gnuletik/puppeteer-heroku-buildpack-fonts

Thanks again!

**Comment by jonknapp** [comment]
Thanks again; I updated the README of this project and will archiving it later this week. You just saved me the time I needed to get a few client projects eventually updated. :)

**Pull request closed without merging**
